title: ol-rotate-feature
description: Rotate feature interaction for OpenLayers
google_analytics: UA-98870917-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
  - jekyll-redirect-from
